#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v18
# autospec commit: 356da62
#
Name     : R-bslib
Version  : 0.8.0
Release  : 28
URL      : https://cran.r-project.org/src/contrib/bslib_0.8.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bslib_0.8.0.tar.gz
Summary  : Custom 'Bootstrap' 'Sass' Themes for 'shiny' and 'rmarkdown'
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: R-bslib-license = %{version}-%{release}
Requires: R-base64enc
Requires: R-cachem
Requires: R-fastmap
Requires: R-htmltools
Requires: R-jquerylib
Requires: R-jsonlite
Requires: R-lifecycle
Requires: R-memoise
Requires: R-mime
Requires: R-rlang
Requires: R-sass
BuildRequires : R-base64enc
BuildRequires : R-cachem
BuildRequires : R-fastmap
BuildRequires : R-htmltools
BuildRequires : R-jquerylib
BuildRequires : R-jsonlite
BuildRequires : R-lifecycle
BuildRequires : R-memoise
BuildRequires : R-mime
BuildRequires : R-rlang
BuildRequires : R-sass
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
'rmarkdown' via 'Bootstrap' 'Sass'. Supports 'Bootstrap' 3, 4 and 5 as
    well as their various 'Bootswatch' themes. An interactive widget is
    also provided for previewing themes in real time.

%package license
Summary: license components for the R-bslib package.
Group: Default

%description license
license components for the R-bslib package.


%prep
%setup -q -n bslib
pushd ..
cp -a bslib buildavx2
popd
pushd ..
cp -a bslib buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722297937

%install
export SOURCE_DATE_EPOCH=1722297937
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-bslib
cp %{_builddir}/bslib/LICENSE.note %{buildroot}/usr/share/package-licenses/R-bslib/a8486c06ebb6e9b1e40a9a3c36cc32e99b840fd4 || :
cp %{_builddir}/bslib/inst/lib/bs-a11y-p/LICENSE.md %{buildroot}/usr/share/package-licenses/R-bslib/749d4a78e5c5b492bdc10eef93a9e5d9f4c0de0a || :
cp %{_builddir}/bslib/inst/lib/bs-colorpicker/LICENSE %{buildroot}/usr/share/package-licenses/R-bslib/86ce50765f0a3c0942a1546cdde442ff56c05d0e || :
cp %{_builddir}/bslib/inst/lib/bs3/LICENSE %{buildroot}/usr/share/package-licenses/R-bslib/ebcab2dc61dad9f3fbf7867a00b1557da86f2218 || :
cp %{_builddir}/bslib/inst/lib/bs4/LICENSE %{buildroot}/usr/share/package-licenses/R-bslib/1174fef9dbf57763afe6311112cb63f9a0679acd || :
cp %{_builddir}/bslib/inst/lib/bs5/LICENSE %{buildroot}/usr/share/package-licenses/R-bslib/84e0cfb08dfbdc5c6c146c0e57de93c81ef18c56 || :
cp %{_builddir}/bslib/inst/lib/bsw3/LICENSE %{buildroot}/usr/share/package-licenses/R-bslib/94cb9d2782f0f9d8fc1fa7826d44bb60753bbac6 || :
cp %{_builddir}/bslib/inst/lib/bsw4/LICENSE %{buildroot}/usr/share/package-licenses/R-bslib/94cb9d2782f0f9d8fc1fa7826d44bb60753bbac6 || :
cp %{_builddir}/bslib/inst/lib/bsw5/LICENSE %{buildroot}/usr/share/package-licenses/R-bslib/94cb9d2782f0f9d8fc1fa7826d44bb60753bbac6 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bslib/DESCRIPTION
/usr/lib64/R/library/bslib/INDEX
/usr/lib64/R/library/bslib/LICENSE
/usr/lib64/R/library/bslib/Meta/Rd.rds
/usr/lib64/R/library/bslib/Meta/features.rds
/usr/lib64/R/library/bslib/Meta/hsearch.rds
/usr/lib64/R/library/bslib/Meta/links.rds
/usr/lib64/R/library/bslib/Meta/nsInfo.rds
/usr/lib64/R/library/bslib/Meta/package.rds
/usr/lib64/R/library/bslib/NAMESPACE
/usr/lib64/R/library/bslib/NEWS.md
/usr/lib64/R/library/bslib/R/bslib
/usr/lib64/R/library/bslib/R/bslib.rdb
/usr/lib64/R/library/bslib/R/bslib.rdx
/usr/lib64/R/library/bslib/R/sysdata.rdb
/usr/lib64/R/library/bslib/R/sysdata.rdx
/usr/lib64/R/library/bslib/bs3compat/_declarations.scss
/usr/lib64/R/library/bslib/bs3compat/_defaults.scss
/usr/lib64/R/library/bslib/bs3compat/_dropdown_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_dt_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_glyphicons.scss
/usr/lib64/R/library/bslib/bs3compat/_headers.scss
/usr/lib64/R/library/bslib/bs3compat/_help_text.scss
/usr/lib64/R/library/bslib/bs3compat/_nav_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_navbar_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_progress_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_rules.scss
/usr/lib64/R/library/bslib/bs3compat/_shiny_input.scss
/usr/lib64/R/library/bslib/bs3compat/_shiny_misc.scss
/usr/lib64/R/library/bslib/bs3compat/_wells.scss
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.eot
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.svg
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.ttf
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.woff
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.woff2
/usr/lib64/R/library/bslib/bs3compat/js/bs3compat.js
/usr/lib64/R/library/bslib/bs3compat/js/tabs.js
/usr/lib64/R/library/bslib/bs3compat/js/transition.js
/usr/lib64/R/library/bslib/bslib-scss/bslib.scss
/usr/lib64/R/library/bslib/bslib-scss/color-utilities.scss
/usr/lib64/R/library/bslib/bslib-scss/functions.scss
/usr/lib64/R/library/bslib/bslib-scss/spacer.scss
/usr/lib64/R/library/bslib/bslib-scss/tab-fill.scss
/usr/lib64/R/library/bslib/builtin/bs5/shiny/_mixins.scss
/usr/lib64/R/library/bslib/builtin/bs5/shiny/_rules.scss
/usr/lib64/R/library/bslib/builtin/bs5/shiny/_variables.scss
/usr/lib64/R/library/bslib/builtin/bs5/shiny/font.css
/usr/lib64/R/library/bslib/builtin/bs5/shiny/ionrangeslider/_rules.scss
/usr/lib64/R/library/bslib/builtin/bs5/shiny/ionrangeslider/_variables.scss
/usr/lib64/R/library/bslib/builtin/bs5/shiny/tables/_rules.scss
/usr/lib64/R/library/bslib/components/dist/components.css
/usr/lib64/R/library/bslib/components/dist/components.js
/usr/lib64/R/library/bslib/components/dist/components.js.map
/usr/lib64/R/library/bslib/components/dist/components.min.js
/usr/lib64/R/library/bslib/components/dist/components.min.js.map
/usr/lib64/R/library/bslib/components/dist/web-components.js
/usr/lib64/R/library/bslib/components/dist/web-components.js.map
/usr/lib64/R/library/bslib/components/dist/web-components.min.js
/usr/lib64/R/library/bslib/components/dist/web-components.min.js.map
/usr/lib64/R/library/bslib/components/dist/webComponents/webComponents.min.js
/usr/lib64/R/library/bslib/components/scss/accordion.scss
/usr/lib64/R/library/bslib/components/scss/card.scss
/usr/lib64/R/library/bslib/components/scss/grid.scss
/usr/lib64/R/library/bslib/components/scss/mixins/_mixins.scss
/usr/lib64/R/library/bslib/components/scss/nav_spacer.scss
/usr/lib64/R/library/bslib/components/scss/page_fillable.scss
/usr/lib64/R/library/bslib/components/scss/page_navbar.scss
/usr/lib64/R/library/bslib/components/scss/page_sidebar.scss
/usr/lib64/R/library/bslib/components/scss/sidebar.scss
/usr/lib64/R/library/bslib/components/scss/value_box.scss
/usr/lib64/R/library/bslib/components/tag-require.js
/usr/lib64/R/library/bslib/css-precompiled/3/bootstrap.min.css
/usr/lib64/R/library/bslib/css-precompiled/4/bootstrap.min.css
/usr/lib64/R/library/bslib/css-precompiled/5/bootstrap.min.css
/usr/lib64/R/library/bslib/css-precompiled/5/bootstrap.scss
/usr/lib64/R/library/bslib/custom/person.scss
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/R/code_modal.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/R/colors.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/R/mod-global-controls.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/R/mod-selextra.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/R/mod-value-box-ui.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/R/random_plot.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/R/random_values.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/R/shuffleButton.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/about-value-boxes.md
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/app.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/deploy.R
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/www/build-a-box.js
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/www/build-a-box.scss
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/www/code-modal.js
/usr/lib64/R/library/bslib/examples-shiny/build-a-box/www/shiny.png
/usr/lib64/R/library/bslib/examples-shiny/card/app.R
/usr/lib64/R/library/bslib/examples-shiny/card/deploy.R
/usr/lib64/R/library/bslib/examples-shiny/card/www/shiny-hex.svg
/usr/lib64/R/library/bslib/examples-shiny/flights/app.R
/usr/lib64/R/library/bslib/examples-shiny/flights/deploy.R
/usr/lib64/R/library/bslib/examples-shiny/flights/www/logo.png
/usr/lib64/R/library/bslib/examples-shiny/value_box/app.R
/usr/lib64/R/library/bslib/examples-shiny/value_box/deploy.R
/usr/lib64/R/library/bslib/fonts/07d40e985ad7c747025dabb9f22142c4.woff2
/usr/lib64/R/library/bslib/fonts/1Ptug8zYS_SKggPNyC0ITw.woff2
/usr/lib64/R/library/bslib/fonts/1Ptug8zYS_SKggPNyCAIT5lu.woff2
/usr/lib64/R/library/bslib/fonts/1Ptug8zYS_SKggPNyCIIT5lu.woff2
/usr/lib64/R/library/bslib/fonts/1Ptug8zYS_SKggPNyCMIT5lu.woff2
/usr/lib64/R/library/bslib/fonts/1Ptug8zYS_SKggPNyCkIT5lu.woff2
/usr/lib64/R/library/bslib/fonts/1f5e011d6aae0d98fc0518e1a303e99a.woff2
/usr/lib64/R/library/bslib/fonts/4iCs6KVjbNBYlgoKcQ72j00.woff2
/usr/lib64/R/library/bslib/fonts/4iCs6KVjbNBYlgoKcg72j00.woff2
/usr/lib64/R/library/bslib/fonts/4iCs6KVjbNBYlgoKcw72j00.woff2
/usr/lib64/R/library/bslib/fonts/4iCs6KVjbNBYlgoKew72j00.woff2
/usr/lib64/R/library/bslib/fonts/4iCs6KVjbNBYlgoKfA72j00.woff2
/usr/lib64/R/library/bslib/fonts/4iCs6KVjbNBYlgoKfw72.woff2
/usr/lib64/R/library/bslib/fonts/4iCv6KVjbNBYlgoCxCvjs2yNL4U.woff2
/usr/lib64/R/library/bslib/fonts/4iCv6KVjbNBYlgoCxCvjsGyN.woff2
/usr/lib64/R/library/bslib/fonts/4iCv6KVjbNBYlgoCxCvjtGyNL4U.woff2
/usr/lib64/R/library/bslib/fonts/4iCv6KVjbNBYlgoCxCvjvGyNL4U.woff2
/usr/lib64/R/library/bslib/fonts/4iCv6KVjbNBYlgoCxCvjvWyNL4U.woff2
/usr/lib64/R/library/bslib/fonts/4iCv6KVjbNBYlgoCxCvjvmyNL4U.woff2
/usr/lib64/R/library/bslib/fonts/626330658504e338ee86aec8e957426b.woff2
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7jsDJT9g.woff2
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7ksDJT9g.woff2
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7nsDI.woff2
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7osDJT9g.woff2
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7psDJT9g.woff2
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7qsDJT9g.woff2
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7rsDJT9g.woff2
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qN67lqDY.woff2
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qNK7lqDY.woff2
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qNa7lqDY.woff2
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qNq7lqDY.woff2
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qO67lqDY.woff2
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7l.woff2
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qPK7lqDY.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwkxduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwlBduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwlxdu.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwmBduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwmRduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwmhduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwmxduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwkxduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwlBduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwlxdu.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwmBduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwmRduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwmhduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwmxduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwkxduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlBduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdu.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwmBduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwmRduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwmhduz8A.woff2
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwmxduz8A.woff2
/usr/lib64/R/library/bslib/fonts/CSR54z1Qlv-GDxkbKVQ_dFsvWNReuQ.woff2
/usr/lib64/R/library/bslib/fonts/CSR54z1Qlv-GDxkbKVQ_dFsvWNpeudwk.woff2
/usr/lib64/R/library/bslib/fonts/CSR64z1Qlv-GDxkbKVQ_fO4KTet_.woff2
/usr/lib64/R/library/bslib/fonts/CSR64z1Qlv-GDxkbKVQ_fOAKTQ.woff2
/usr/lib64/R/library/bslib/fonts/HI_QiYsKILxRpg3hIP6sJ7fM7PqlONvQlMIXxw.woff2
/usr/lib64/R/library/bslib/fonts/HI_QiYsKILxRpg3hIP6sJ7fM7PqlONvUlMI.woff2
/usr/lib64/R/library/bslib/fonts/HI_QiYsKILxRpg3hIP6sJ7fM7PqlONvXlMIXxw.woff2
/usr/lib64/R/library/bslib/fonts/HI_QiYsKILxRpg3hIP6sJ7fM7PqlONvYlMIXxw.woff2
/usr/lib64/R/library/bslib/fonts/HI_QiYsKILxRpg3hIP6sJ7fM7PqlONvZlMIXxw.woff2
/usr/lib64/R/library/bslib/fonts/HI_QiYsKILxRpg3hIP6sJ7fM7PqlONvalMIXxw.woff2
/usr/lib64/R/library/bslib/fonts/HI_QiYsKILxRpg3hIP6sJ7fM7PqlONvblMIXxw.woff2
/usr/lib64/R/library/bslib/fonts/HI_SiYsKILxRpg3hIP6sJ7fM7PqlM-vWjMY.woff2
/usr/lib64/R/library/bslib/fonts/HI_SiYsKILxRpg3hIP6sJ7fM7PqlMOvWjMY.woff2
/usr/lib64/R/library/bslib/fonts/HI_SiYsKILxRpg3hIP6sJ7fM7PqlMevWjMY.woff2
/usr/lib64/R/library/bslib/fonts/HI_SiYsKILxRpg3hIP6sJ7fM7PqlMuvWjMY.woff2
/usr/lib64/R/library/bslib/fonts/HI_SiYsKILxRpg3hIP6sJ7fM7PqlOevWjMY.woff2
/usr/lib64/R/library/bslib/fonts/HI_SiYsKILxRpg3hIP6sJ7fM7PqlPevW.woff2
/usr/lib64/R/library/bslib/fonts/HI_SiYsKILxRpg3hIP6sJ7fM7PqlPuvWjMY.woff2
/usr/lib64/R/library/bslib/fonts/JTUSjIg1_i6t8kCHKm459W1hyzbi.woff2
/usr/lib64/R/library/bslib/fonts/JTUSjIg1_i6t8kCHKm459WRhyzbi.woff2
/usr/lib64/R/library/bslib/fonts/JTUSjIg1_i6t8kCHKm459WZhyzbi.woff2
/usr/lib64/R/library/bslib/fonts/JTUSjIg1_i6t8kCHKm459Wdhyzbi.woff2
/usr/lib64/R/library/bslib/fonts/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9fABc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9fBBc4.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9fBxc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9fCBc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9fCRc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9fChc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9fCxc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5fABc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5fBBc4.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5fBxc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5fCBc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5fCRc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5fChc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5fCxc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlfABc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlfBBc4.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlfBxc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlfCBc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlfCRc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlfChc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlfCxc4EsA.woff2
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Mu4WxKOzY.woff2
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Mu4mxK.woff2
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Mu5mxKOzY.woff2
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Mu72xKOzY.woff2
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Mu7GxKOzY.woff2
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Mu7WxKOzY.woff2
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Mu7mxKOzY.woff2
/usr/lib64/R/library/bslib/fonts/QGYpz_kZZAGCONcK2A4bGOj8mNhN.woff2
/usr/lib64/R/library/bslib/fonts/S6u8w4BMUTPHjxsAUi-qJCY.woff2
/usr/lib64/R/library/bslib/fonts/S6u8w4BMUTPHjxsAXC-q.woff2
/usr/lib64/R/library/bslib/fonts/S6u9w4BMUTPHh6UVSwaPGR_p.woff2
/usr/lib64/R/library/bslib/fonts/S6u9w4BMUTPHh6UVSwiPGQ.woff2
/usr/lib64/R/library/bslib/fonts/S6u9w4BMUTPHh7USSwaPGR_p.woff2
/usr/lib64/R/library/bslib/fonts/S6u9w4BMUTPHh7USSwiPGQ.woff2
/usr/lib64/R/library/bslib/fonts/S6uyw4BMUTPHjx4wXg.woff2
/usr/lib64/R/library/bslib/fonts/S6uyw4BMUTPHjxAwXjeu.woff2
/usr/lib64/R/library/bslib/fonts/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa0ZL7SUc.woff2
/usr/lib64/R/library/bslib/fonts/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2
/usr/lib64/R/library/bslib/fonts/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1pL7SUc.woff2
/usr/lib64/R/library/bslib/fonts/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa25L7SUc.woff2
/usr/lib64/R/library/bslib/fonts/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2JL7SUc.woff2
/usr/lib64/R/library/bslib/fonts/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2ZL7SUc.woff2
/usr/lib64/R/library/bslib/fonts/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7SUc.woff2
/usr/lib64/R/library/bslib/fonts/XRXV3I6Li01BKofIMeaBXso.woff2
/usr/lib64/R/library/bslib/fonts/XRXV3I6Li01BKofINeaB.woff2
/usr/lib64/R/library/bslib/fonts/XRXV3I6Li01BKofIO-aBXso.woff2
/usr/lib64/R/library/bslib/fonts/XRXV3I6Li01BKofIOOaBXso.woff2
/usr/lib64/R/library/bslib/fonts/XRXV3I6Li01BKofIOuaBXso.woff2
/usr/lib64/R/library/bslib/fonts/c2f002b3a87d3f9bfeebb23d32cfd9f8.woff2
/usr/lib64/R/library/bslib/fonts/ee91700cdbf7ce16c054c2bb8946c736.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqW106F15M.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWt06F15M.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWtE6F15M.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWtU6F15M.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWtk6F15M.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWu06F15M.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWuU6F.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWuk6F15M.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWvU6F15M.woff2
/usr/lib64/R/library/bslib/fonts/memtYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWqWxU6F15M.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS-muw.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTS2mu1aB.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSCmu1aB.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSGmu1aB.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSKmu1aB.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSOmu1aB.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSumu1aB.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTSymu1aB.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTUGmu1aB.woff2
/usr/lib64/R/library/bslib/fonts/memvYaGs126MiZpBA-UvWbX2vVnXBbObj2OVTVOmu1aB.woff2
/usr/lib64/R/library/bslib/fonts/q5uGsou0JOdh94bfuQltOxU.woff2
/usr/lib64/R/library/bslib/fonts/q5uGsou0JOdh94bfvQlt.woff2
/usr/lib64/R/library/bslib/help/AnIndex
/usr/lib64/R/library/bslib/help/aliases.rds
/usr/lib64/R/library/bslib/help/bslib.rdb
/usr/lib64/R/library/bslib/help/bslib.rdx
/usr/lib64/R/library/bslib/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/bslib/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/bslib/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/bslib/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/bslib/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/bslib/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/bslib/help/figures/lifecycle-soft-deprecated.svg
/usr/lib64/R/library/bslib/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/bslib/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/bslib/help/figures/navset-card-pill.png
/usr/lib64/R/library/bslib/help/figures/navset-card-underline.png
/usr/lib64/R/library/bslib/help/figures/navset-pill-list.png
/usr/lib64/R/library/bslib/help/figures/navset-pill.png
/usr/lib64/R/library/bslib/help/figures/navset-tab-basic.png
/usr/lib64/R/library/bslib/help/figures/navset-tab-card.png
/usr/lib64/R/library/bslib/help/figures/navset-tab.png
/usr/lib64/R/library/bslib/help/figures/navset-underline.png
/usr/lib64/R/library/bslib/help/figures/navset_card_pill.png
/usr/lib64/R/library/bslib/help/figures/page-navbar.png
/usr/lib64/R/library/bslib/help/figures/value-box-background-color.png
/usr/lib64/R/library/bslib/help/figures/value-box-background-theme.png
/usr/lib64/R/library/bslib/help/figures/value-box-custom.png
/usr/lib64/R/library/bslib/help/figures/value-box-gradient-1.png
/usr/lib64/R/library/bslib/help/figures/value-box-named-color.png
/usr/lib64/R/library/bslib/help/figures/value-box-named-theme.png
/usr/lib64/R/library/bslib/help/figures/value-box-showcase-bottom.png
/usr/lib64/R/library/bslib/help/figures/value-box-showcase-left-center.png
/usr/lib64/R/library/bslib/help/figures/value-box-showcase-top-right.png
/usr/lib64/R/library/bslib/help/figures/value-box-text-color.png
/usr/lib64/R/library/bslib/help/figures/value-box-text-theme.png
/usr/lib64/R/library/bslib/help/figures/value-box-theme-class.png
/usr/lib64/R/library/bslib/help/paths.rds
/usr/lib64/R/library/bslib/html/00Index.html
/usr/lib64/R/library/bslib/html/R.css
/usr/lib64/R/library/bslib/lib/bs-a11y-p/LICENSE.md
/usr/lib64/R/library/bslib/lib/bs-a11y-p/package.json
/usr/lib64/R/library/bslib/lib/bs-a11y-p/plugins/css/bootstrap-accessibility.css
/usr/lib64/R/library/bslib/lib/bs-a11y-p/plugins/js/bootstrap-accessibility.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/plugins/js/bootstrap-accessibility.min.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/carousel.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/collapse.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/dropdown.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/functions.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/modal.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/tab.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/bootstrap-accessibility.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/alerts.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/buttons.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/carousel.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/close.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/divs.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/links.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/mixins.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/navigation.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/variables.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/meteor/package.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/bootstrap-accessibility.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_alerts.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_carousel.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_close.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_divs.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_links.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_mixins.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_navigation.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_variables.scss
/usr/lib64/R/library/bslib/lib/bs-colorpicker/LICENSE
/usr/lib64/R/library/bslib/lib/bs-colorpicker/README.md
/usr/lib64/R/library/bslib/lib/bs-colorpicker/css/bootstrap-colorpicker.css
/usr/lib64/R/library/bslib/lib/bs-colorpicker/css/bootstrap-colorpicker.css.map
/usr/lib64/R/library/bslib/lib/bs-colorpicker/css/bootstrap-colorpicker.min.css
/usr/lib64/R/library/bslib/lib/bs-colorpicker/css/bootstrap-colorpicker.min.css.map
/usr/lib64/R/library/bslib/lib/bs-colorpicker/js/bootstrap-colorpicker.js
/usr/lib64/R/library/bslib/lib/bs-colorpicker/js/bootstrap-colorpicker.js.map
/usr/lib64/R/library/bslib/lib/bs-colorpicker/js/bootstrap-colorpicker.min.js.map
/usr/lib64/R/library/bslib/lib/bs-colorpicker/package.json
/usr/lib64/R/library/bslib/lib/bs3/CHANGELOG.md
/usr/lib64/R/library/bslib/lib/bs3/LICENSE
/usr/lib64/R/library/bslib/lib/bs3/README.md
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.svg
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap-sprockets.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap.min.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/affix.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/alert.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/button.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/carousel.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/collapse.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/dropdown.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/modal.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/popover.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/scrollspy.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/tab.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/tooltip.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/transition.js
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/_bootstrap-compass.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/_bootstrap-mincer.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/_bootstrap-sprockets.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/_bootstrap.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_alerts.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_badges.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_breadcrumbs.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_button-groups.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_carousel.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_close.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_code.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_component-animations.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_dropdowns.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_forms.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_glyphicons.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_grid.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_input-groups.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_jumbotron.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_labels.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_media.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_mixins.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_modals.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_navbar.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_navs.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_normalize.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_pager.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_panels.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_popovers.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_print.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_progress-bars.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_responsive-embed.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_responsive-utilities.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_scaffolding.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_tables.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_theme.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_thumbnails.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_tooltip.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_type.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_utilities.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_variables.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_wells.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_alerts.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_background-variant.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_border-radius.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_center-block.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_forms.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_gradients.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_grid-framework.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_grid.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_hide-text.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_image.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_labels.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_nav-divider.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_nav-vertical-align.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_opacity.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_panels.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_progress-bar.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_reset-filter.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_reset-text.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_resize.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_responsive-visibility.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_size.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_tab-focus.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_table-row.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_text-emphasis.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_text-overflow.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_vendor-prefixes.scss
/usr/lib64/R/library/bslib/lib/bs3/eyeglass-exports.js
/usr/lib64/R/library/bslib/lib/bs3/package.json
/usr/lib64/R/library/bslib/lib/bs4/LICENSE
/usr/lib64/R/library/bslib/lib/bs4/README.md
/usr/lib64/R/library/bslib/lib/bs4/dist/js/bootstrap.bundle.min.js
/usr/lib64/R/library/bslib/lib/bs4/dist/js/bootstrap.bundle.min.js.map
/usr/lib64/R/library/bslib/lib/bs4/package.json
/usr/lib64/R/library/bslib/lib/bs4/scss/_alert.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_badge.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_breadcrumb.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_button-group.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_card.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_carousel.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_close.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_code.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_custom-forms.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_deprecated.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_dropdown.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_forms.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_functions.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_grid.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_images.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_input-group.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_jumbotron.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_media.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_mixins.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_modal.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_nav.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_navbar.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_popover.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_print.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_progress.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_reboot.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_root.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_spinners.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_tables.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_toasts.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_tooltip.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_transitions.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_type.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_utilities.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_variables.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/bootstrap-grid.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/bootstrap-reboot.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/bootstrap.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_alert.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_background-variant.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_badge.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_border-radius.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_box-shadow.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_breakpoints.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_caret.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_deprecate.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_float.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_forms.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_gradients.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_grid-framework.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_grid.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_hover.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_image.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_lists.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_nav-divider.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_reset-text.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_resize.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_screen-reader.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_size.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_table-row.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_text-emphasis.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_text-hide.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_text-truncate.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_transition.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_visibility.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_align.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_background.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_borders.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_display.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_embed.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_flex.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_float.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_interactions.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_overflow.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_position.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_screenreaders.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_shadows.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_sizing.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_spacing.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_stretched-link.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_text.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_visibility.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/vendor/_rfs.scss
/usr/lib64/R/library/bslib/lib/bs5/LICENSE
/usr/lib64/R/library/bslib/lib/bs5/README.md
/usr/lib64/R/library/bslib/lib/bs5/dist/js/bootstrap.bundle.min.js
/usr/lib64/R/library/bslib/lib/bs5/dist/js/bootstrap.bundle.min.js.map
/usr/lib64/R/library/bslib/lib/bs5/package.json
/usr/lib64/R/library/bslib/lib/bs5/scss/_accordion.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_alert.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_badge.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_breadcrumb.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_button-group.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_card.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_carousel.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_close.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_containers.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_dropdown.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_forms.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_functions.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_grid.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_helpers.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_images.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_maps.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_mixins.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_modal.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_nav.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_navbar.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_offcanvas.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_placeholders.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_popover.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_progress.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_reboot.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_root.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_spinners.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_tables.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_toasts.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_tooltip.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_transitions.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_type.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_utilities.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_variables-dark.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_variables.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/bootstrap-grid.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/bootstrap-reboot.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/bootstrap-utilities.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/bootstrap.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_floating-labels.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-check.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-control.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-range.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-select.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-text.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_input-group.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_labels.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_validation.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_color-bg.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_colored-links.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_focus-ring.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_icon-link.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_position.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_ratio.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_stacks.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_stretched-link.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_text-truncation.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_visually-hidden.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_vr.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_alert.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_backdrop.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_banner.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_border-radius.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_box-shadow.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_breakpoints.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_caret.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_color-mode.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_color-scheme.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_container.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_deprecate.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_forms.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_gradients.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_grid.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_image.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_lists.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_reset-text.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_resize.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_table-variants.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_text-truncate.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_transition.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_utilities.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_visually-hidden.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/utilities/_api.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/vendor/_rfs.scss
/usr/lib64/R/library/bslib/lib/bsw3/LICENSE
/usr/lib64/R/library/bslib/lib/bsw3/README.md
/usr/lib64/R/library/bslib/lib/bsw3/cerulean/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/cerulean/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/cosmo/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/cosmo/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/cosmo/font.css
/usr/lib64/R/library/bslib/lib/bsw3/cyborg/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/cyborg/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/cyborg/font.css
/usr/lib64/R/library/bslib/lib/bsw3/darkly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/darkly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/darkly/font.css
/usr/lib64/R/library/bslib/lib/bsw3/flatly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/flatly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/flatly/font.css
/usr/lib64/R/library/bslib/lib/bsw3/journal/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/journal/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/journal/font.css
/usr/lib64/R/library/bslib/lib/bsw3/lumen/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/lumen/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/lumen/font.css
/usr/lib64/R/library/bslib/lib/bsw3/package.json
/usr/lib64/R/library/bslib/lib/bsw3/paper/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/paper/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/paper/font.css
/usr/lib64/R/library/bslib/lib/bsw3/readable/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/readable/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/readable/font.css
/usr/lib64/R/library/bslib/lib/bsw3/sandstone/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/sandstone/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/sandstone/font.css
/usr/lib64/R/library/bslib/lib/bsw3/simplex/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/simplex/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/simplex/font.css
/usr/lib64/R/library/bslib/lib/bsw3/slate/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/slate/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/spacelab/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/spacelab/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/spacelab/font.css
/usr/lib64/R/library/bslib/lib/bsw3/superhero/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/superhero/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/superhero/font.css
/usr/lib64/R/library/bslib/lib/bsw3/united/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/united/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/united/font.css
/usr/lib64/R/library/bslib/lib/bsw3/yeti/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/yeti/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/yeti/font.css
/usr/lib64/R/library/bslib/lib/bsw4/LICENSE
/usr/lib64/R/library/bslib/lib/bsw4/README.md
/usr/lib64/R/library/bslib/lib/bsw4/dist/cerulean/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cerulean/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cosmo/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cosmo/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cosmo/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/cyborg/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cyborg/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cyborg/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/darkly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/darkly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/darkly/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/flatly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/flatly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/flatly/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/journal/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/journal/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/journal/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/litera/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/litera/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lumen/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lumen/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lumen/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/lux/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lux/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lux/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/materia/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/materia/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/materia/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/minty/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/minty/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/minty/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/pulse/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/pulse/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sandstone/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sandstone/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sandstone/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/simplex/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/simplex/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/simplex/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/sketchy/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sketchy/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sketchy/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/slate/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/slate/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/solar/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/solar/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/solar/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/spacelab/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/spacelab/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/spacelab/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/superhero/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/superhero/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/superhero/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/united/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/united/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/united/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/yeti/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/yeti/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/yeti/font.css
/usr/lib64/R/library/bslib/lib/bsw4/package.json
/usr/lib64/R/library/bslib/lib/bsw5/LICENSE
/usr/lib64/R/library/bslib/lib/bsw5/README.md
/usr/lib64/R/library/bslib/lib/bsw5/dist/cerulean/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cerulean/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cosmo/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cosmo/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cosmo/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/cyborg/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cyborg/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cyborg/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/darkly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/darkly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/darkly/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/flatly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/flatly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/flatly/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/journal/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/journal/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/journal/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/litera/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/litera/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lumen/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lumen/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lumen/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/lux/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lux/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lux/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/materia/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/materia/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/materia/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/minty/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/minty/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/minty/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/morph/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/morph/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/morph/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/pulse/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/pulse/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/quartz/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/quartz/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sandstone/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sandstone/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sandstone/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/simplex/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/simplex/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/simplex/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/sketchy/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sketchy/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sketchy/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/slate/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/slate/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/solar/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/solar/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/solar/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/spacelab/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/spacelab/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/spacelab/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/superhero/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/superhero/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/superhero/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/united/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/united/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/united/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/vapor/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/vapor/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/vapor/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/yeti/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/yeti/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/yeti/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/zephyr/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/zephyr/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/zephyr/font.css
/usr/lib64/R/library/bslib/lib/bsw5/package.json
/usr/lib64/R/library/bslib/package.json
/usr/lib64/R/library/bslib/rmarkdown/templates/legacy/skeleton/skeleton.Rmd
/usr/lib64/R/library/bslib/rmarkdown/templates/legacy/template.yaml
/usr/lib64/R/library/bslib/rmarkdown/templates/new/skeleton/skeleton.Rmd
/usr/lib64/R/library/bslib/rmarkdown/templates/new/template.yaml
/usr/lib64/R/library/bslib/rmarkdown/templates/real-time/skeleton/skeleton.Rmd
/usr/lib64/R/library/bslib/rmarkdown/templates/real-time/template.yaml
/usr/lib64/R/library/bslib/sass-utils/color-contrast.scss
/usr/lib64/R/library/bslib/tests/testthat.R
/usr/lib64/R/library/bslib/tests/testthat/_snaps/bs-theme-preset-builtin.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/bs-theme-preset.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/card.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/fill.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/layout.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/page.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/page/card.html
/usr/lib64/R/library/bslib/tests/testthat/_snaps/page/modern-page.html
/usr/lib64/R/library/bslib/tests/testthat/_snaps/value-box.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/zzzz-bs-sass.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/zzzz-bs-sass/bs4-imports
/usr/lib64/R/library/bslib/tests/testthat/_snaps/zzzz-bs-sass/bs5-imports
/usr/lib64/R/library/bslib/tests/testthat/helper-cache.R
/usr/lib64/R/library/bslib/tests/testthat/helper-css.R
/usr/lib64/R/library/bslib/tests/testthat/helper-files.R
/usr/lib64/R/library/bslib/tests/testthat/helper-fill.R
/usr/lib64/R/library/bslib/tests/testthat/helper-seed.R
/usr/lib64/R/library/bslib/tests/testthat/test-bs-theme-preset-bootswatch.R
/usr/lib64/R/library/bslib/tests/testthat/test-bs-theme-preset-builtin.R
/usr/lib64/R/library/bslib/tests/testthat/test-bs-theme-preset.R
/usr/lib64/R/library/bslib/tests/testthat/test-bs-theme.R
/usr/lib64/R/library/bslib/tests/testthat/test-bs4-deps.R
/usr/lib64/R/library/bslib/tests/testthat/test-card.R
/usr/lib64/R/library/bslib/tests/testthat/test-fill.R
/usr/lib64/R/library/bslib/tests/testthat/test-fonts.R
/usr/lib64/R/library/bslib/tests/testthat/test-global.R
/usr/lib64/R/library/bslib/tests/testthat/test-layout.R
/usr/lib64/R/library/bslib/tests/testthat/test-page.R
/usr/lib64/R/library/bslib/tests/testthat/test-remove.R
/usr/lib64/R/library/bslib/tests/testthat/test-rmd-skeletons.R
/usr/lib64/R/library/bslib/tests/testthat/test-shiny-devmode.R
/usr/lib64/R/library/bslib/tests/testthat/test-sidebar.R
/usr/lib64/R/library/bslib/tests/testthat/test-theme-base-colors.R
/usr/lib64/R/library/bslib/tests/testthat/test-theme-bootswatch.R
/usr/lib64/R/library/bslib/tests/testthat/test-theme-update.R
/usr/lib64/R/library/bslib/tests/testthat/test-theme-version.R
/usr/lib64/R/library/bslib/tests/testthat/test-utils.R
/usr/lib64/R/library/bslib/tests/testthat/test-value-box.R
/usr/lib64/R/library/bslib/tests/testthat/test-zzz-bs.R
/usr/lib64/R/library/bslib/tests/testthat/test-zzz-precompile.R
/usr/lib64/R/library/bslib/tests/testthat/test-zzzz-bs-sass.R
/usr/lib64/R/library/bslib/themer-demo/R/tips.R
/usr/lib64/R/library/bslib/themer-demo/app.R
/usr/lib64/R/library/bslib/themer-demo/deploy.R
/usr/lib64/R/library/bslib/themer-demo/deploy/app.R
/usr/lib64/R/library/bslib/themer-demo/global.R
/usr/lib64/R/library/bslib/themer/options.json
/usr/lib64/R/library/bslib/themer/themer.js
/usr/lib64/R/library/bslib/themer/themer.scss

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-bslib/1174fef9dbf57763afe6311112cb63f9a0679acd
/usr/share/package-licenses/R-bslib/749d4a78e5c5b492bdc10eef93a9e5d9f4c0de0a
/usr/share/package-licenses/R-bslib/84e0cfb08dfbdc5c6c146c0e57de93c81ef18c56
/usr/share/package-licenses/R-bslib/86ce50765f0a3c0942a1546cdde442ff56c05d0e
/usr/share/package-licenses/R-bslib/94cb9d2782f0f9d8fc1fa7826d44bb60753bbac6
/usr/share/package-licenses/R-bslib/a8486c06ebb6e9b1e40a9a3c36cc32e99b840fd4
/usr/share/package-licenses/R-bslib/ebcab2dc61dad9f3fbf7867a00b1557da86f2218
