#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-bslib
Version  : 0.4.0
Release  : 13
URL      : https://cran.r-project.org/src/contrib/bslib_0.4.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/bslib_0.4.0.tar.gz
Summary  : Custom 'Bootstrap' 'Sass' Themes for 'shiny' and 'rmarkdown'
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: R-cachem
Requires: R-htmltools
Requires: R-jquerylib
Requires: R-jsonlite
Requires: R-memoise
Requires: R-rlang
Requires: R-sass
BuildRequires : R-cachem
BuildRequires : R-htmltools
BuildRequires : R-jquerylib
BuildRequires : R-jsonlite
BuildRequires : R-memoise
BuildRequires : R-rlang
BuildRequires : R-sass
BuildRequires : buildreq-R

%description
<!-- badges: start -->
[![CRAN
status](https://www.r-pkg.org/badges/version/bslib)](https://cran.r-project.org/package=bslib)
[![Lifecycle:
experimental](https://img.shields.io/badge/lifecycle-experimental-orange.svg)](https://lifecycle.r-lib.org/articles/stages.html)
[![R build
status](https://github.com/rstudio/bslib/actions/workflows/R-CMD-check.yaml/badge.svg)](https://github.com/rstudio/bslib/actions)

%prep
%setup -q -c -n bslib
cd %{_builddir}/bslib

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1658095815

%install
export SOURCE_DATE_EPOCH=1658095815
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bslib
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bslib
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library bslib
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc bslib || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/bslib/DESCRIPTION
/usr/lib64/R/library/bslib/INDEX
/usr/lib64/R/library/bslib/LICENSE
/usr/lib64/R/library/bslib/Meta/Rd.rds
/usr/lib64/R/library/bslib/Meta/features.rds
/usr/lib64/R/library/bslib/Meta/hsearch.rds
/usr/lib64/R/library/bslib/Meta/links.rds
/usr/lib64/R/library/bslib/Meta/nsInfo.rds
/usr/lib64/R/library/bslib/Meta/package.rds
/usr/lib64/R/library/bslib/NAMESPACE
/usr/lib64/R/library/bslib/NEWS.md
/usr/lib64/R/library/bslib/R/bslib
/usr/lib64/R/library/bslib/R/bslib.rdb
/usr/lib64/R/library/bslib/R/bslib.rdx
/usr/lib64/R/library/bslib/R/sysdata.rdb
/usr/lib64/R/library/bslib/R/sysdata.rdx
/usr/lib64/R/library/bslib/bs3compat/_declarations.scss
/usr/lib64/R/library/bslib/bs3compat/_defaults.scss
/usr/lib64/R/library/bslib/bs3compat/_dropdown_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_glyphicons.scss
/usr/lib64/R/library/bslib/bs3compat/_headers.scss
/usr/lib64/R/library/bslib/bs3compat/_help_text.scss
/usr/lib64/R/library/bslib/bs3compat/_nav_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_navbar_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_progress_compat.scss
/usr/lib64/R/library/bslib/bs3compat/_rules.scss
/usr/lib64/R/library/bslib/bs3compat/_shiny_input.scss
/usr/lib64/R/library/bslib/bs3compat/_shiny_misc.scss
/usr/lib64/R/library/bslib/bs3compat/_wells.scss
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.eot
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.svg
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.ttf
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.woff
/usr/lib64/R/library/bslib/bs3compat/fonts/glyphicons-halflings-regular.woff2
/usr/lib64/R/library/bslib/bs3compat/js/bs3compat.js
/usr/lib64/R/library/bslib/bs3compat/js/tabs.js
/usr/lib64/R/library/bslib/bs3compat/js/transition.js
/usr/lib64/R/library/bslib/css-precompiled/3/bootstrap.min.css
/usr/lib64/R/library/bslib/css-precompiled/4/bootstrap.min.css
/usr/lib64/R/library/bslib/css-precompiled/5/bootstrap.min.css
/usr/lib64/R/library/bslib/custom/person.scss
/usr/lib64/R/library/bslib/fonts/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVs9pbCIPrc.woff
/usr/lib64/R/library/bslib/fonts/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVvaorCIPrc.woff
/usr/lib64/R/library/bslib/fonts/4iCs6KVjbNBYlgo6ew.woff
/usr/lib64/R/library/bslib/fonts/4iCs6KVjbNBYlgoKfw7w.woff
/usr/lib64/R/library/bslib/fonts/4iCv6KVjbNBYlgoCxCvTtA.woff
/usr/lib64/R/library/bslib/fonts/4iCv6KVjbNBYlgoCxCvjsGyL.woff
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7nsDQ.woff
/usr/lib64/R/library/bslib/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPa7j.woff
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3aPA.woff
/usr/lib64/R/library/bslib/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7j.woff
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rAkw.woff
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vAkw.woff
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwlxdo.woff
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zAkw.woff
/usr/lib64/R/library/bslib/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdo.woff
/usr/lib64/R/library/bslib/fonts/CSR54z1Qlv-GDxkbKVQ_dFsvWNRevw.woff
/usr/lib64/R/library/bslib/fonts/CSR54z1Qlv-GDxkbKVQ_dFsvaNA.woff
/usr/lib64/R/library/bslib/fonts/CSR64z1Qlv-GDxkbKVQ_TOQ.woff
/usr/lib64/R/library/bslib/fonts/CSR64z1Qlv-GDxkbKVQ_fOAKSw.woff
/usr/lib64/R/library/bslib/fonts/JTURjIg1_i6t8kCHKm45_ZpC7g0.woff
/usr/lib64/R/library/bslib/fonts/JTURjIg1_i6t8kCHKm45_dJE7g0.woff
/usr/lib64/R/library/bslib/fonts/JTUSjIg1_i6t8kCHKm45xW0.woff
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9fBBc-.woff
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmEU9vAA.woff
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5fBBc-.woff
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmSU5vAA.woff
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlfBBc-.woff
/usr/lib64/R/library/bslib/fonts/KFOlCnqEu92Fr1MmWUlvAA.woff
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Me5g.woff
/usr/lib64/R/library/bslib/fonts/KFOmCnqEu92Fr1Mu4mxM.woff
/usr/lib64/R/library/bslib/fonts/QGYpz_kZZAGCONcK2A4bGOj8mNhL.woff
/usr/lib64/R/library/bslib/fonts/S6u8w4BMUTPHjxsAXC-s.woff
/usr/lib64/R/library/bslib/fonts/S6u8w4BMUTPHjxswWA.woff
/usr/lib64/R/library/bslib/fonts/S6u9w4BMUTPHh6UVSwiPHw.woff
/usr/lib64/R/library/bslib/fonts/S6u9w4BMUTPHh6UVeww.woff
/usr/lib64/R/library/bslib/fonts/S6u9w4BMUTPHh7USSwiPHw.woff
/usr/lib64/R/library/bslib/fonts/S6u9w4BMUTPHh7USeww.woff
/usr/lib64/R/library/bslib/fonts/S6uyw4BMUTPHjx4wWA.woff
/usr/lib64/R/library/bslib/fonts/S6uyw4BMUTPHvxo.woff
/usr/lib64/R/library/bslib/fonts/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZs.woff
/usr/lib64/R/library/bslib/fonts/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZs.woff
/usr/lib64/R/library/bslib/fonts/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZs.woff
/usr/lib64/R/library/bslib/fonts/XRXV3I6Li01BKof4MQ.woff
/usr/lib64/R/library/bslib/fonts/XRXW3I6Li01BKofA6sKkZQ.woff
/usr/lib64/R/library/bslib/fonts/XRXW3I6Li01BKofAjsOkZQ.woff
/usr/lib64/R/library/bslib/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk5hkWVAexg.woff
/usr/lib64/R/library/bslib/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk5hkaVQ.woff
/usr/lib64/R/library/bslib/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk8ZkWVAexg.woff
/usr/lib64/R/library/bslib/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0Rk8ZkaVQ.woff
/usr/lib64/R/library/bslib/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0RkyFjWVAexg.woff
/usr/lib64/R/library/bslib/fonts/memQYaGs126MiZpBA-UFUIcVXSCEkx2cmqvXlWq8tWZ0Pw86hd0RkyFjaVQ.woff
/usr/lib64/R/library/bslib/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsg-1x4gaVQ.woff
/usr/lib64/R/library/bslib/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsg-1y4k.woff
/usr/lib64/R/library/bslib/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsiH0B4gaVQ.woff
/usr/lib64/R/library/bslib/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsiH0C4k.woff
/usr/lib64/R/library/bslib/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0B4gaVQ.woff
/usr/lib64/R/library/bslib/fonts/memSYaGs126MiZpBA-UvWbX2vVnXBbObj2OVZyOOSr4dVJWUgsjZ0C4k.woff
/usr/lib64/R/library/bslib/fonts/pe03MImSLYBIv1o4X1M8cc9iB_5p.woff
/usr/lib64/R/library/bslib/fonts/pe0qMImSLYBIv1o4X1M8cfe5.woff
/usr/lib64/R/library/bslib/fonts/q5uGsou0JOdh94bfvQlr.woff
/usr/lib64/R/library/bslib/help/AnIndex
/usr/lib64/R/library/bslib/help/aliases.rds
/usr/lib64/R/library/bslib/help/bslib.rdb
/usr/lib64/R/library/bslib/help/bslib.rdx
/usr/lib64/R/library/bslib/help/figures/rstudio-templates.png
/usr/lib64/R/library/bslib/help/paths.rds
/usr/lib64/R/library/bslib/html/00Index.html
/usr/lib64/R/library/bslib/html/R.css
/usr/lib64/R/library/bslib/lib/bs-a11y-p/LICENSE.md
/usr/lib64/R/library/bslib/lib/bs-a11y-p/package.json
/usr/lib64/R/library/bslib/lib/bs-a11y-p/plugins/css/bootstrap-accessibility.css
/usr/lib64/R/library/bslib/lib/bs-a11y-p/plugins/js/bootstrap-accessibility.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/plugins/js/bootstrap-accessibility.min.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/carousel.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/collapse.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/dropdown.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/functions.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/modal.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/js/tab.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/bootstrap-accessibility.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/alerts.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/buttons.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/carousel.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/close.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/divs.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/links.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/mixins.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/navigation.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/less/partials/variables.less
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/meteor/package.js
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/bootstrap-accessibility.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_alerts.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_carousel.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_close.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_divs.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_links.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_mixins.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_navigation.scss
/usr/lib64/R/library/bslib/lib/bs-a11y-p/src/sass/partials/_variables.scss
/usr/lib64/R/library/bslib/lib/bs-colorpicker/LICENSE
/usr/lib64/R/library/bslib/lib/bs-colorpicker/README.md
/usr/lib64/R/library/bslib/lib/bs-colorpicker/css/bootstrap-colorpicker.css
/usr/lib64/R/library/bslib/lib/bs-colorpicker/css/bootstrap-colorpicker.css.map
/usr/lib64/R/library/bslib/lib/bs-colorpicker/css/bootstrap-colorpicker.min.css
/usr/lib64/R/library/bslib/lib/bs-colorpicker/css/bootstrap-colorpicker.min.css.map
/usr/lib64/R/library/bslib/lib/bs-colorpicker/js/bootstrap-colorpicker.js
/usr/lib64/R/library/bslib/lib/bs-colorpicker/js/bootstrap-colorpicker.js.map
/usr/lib64/R/library/bslib/lib/bs-colorpicker/js/bootstrap-colorpicker.min.js
/usr/lib64/R/library/bslib/lib/bs-colorpicker/js/bootstrap-colorpicker.min.js.map
/usr/lib64/R/library/bslib/lib/bs-colorpicker/package.json
/usr/lib64/R/library/bslib/lib/bs3/CHANGELOG.md
/usr/lib64/R/library/bslib/lib/bs3/LICENSE
/usr/lib64/R/library/bslib/lib/bs3/README.md
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.svg
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
/usr/lib64/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap-sprockets.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap.min.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/affix.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/alert.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/button.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/carousel.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/collapse.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/dropdown.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/modal.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/popover.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/scrollspy.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/tab.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/tooltip.js
/usr/lib64/R/library/bslib/lib/bs3/assets/javascripts/bootstrap/transition.js
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/_bootstrap-compass.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/_bootstrap-mincer.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/_bootstrap-sprockets.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/_bootstrap.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_alerts.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_badges.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_breadcrumbs.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_button-groups.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_carousel.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_close.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_code.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_component-animations.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_dropdowns.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_forms.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_glyphicons.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_grid.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_input-groups.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_jumbotron.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_labels.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_media.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_mixins.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_modals.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_navbar.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_navs.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_normalize.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_pager.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_panels.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_popovers.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_print.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_progress-bars.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_responsive-embed.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_responsive-utilities.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_scaffolding.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_tables.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_theme.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_thumbnails.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_tooltip.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_type.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_utilities.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_variables.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/_wells.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_alerts.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_background-variant.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_border-radius.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_center-block.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_forms.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_gradients.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_grid-framework.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_grid.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_hide-text.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_image.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_labels.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_nav-divider.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_nav-vertical-align.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_opacity.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_panels.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_progress-bar.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_reset-filter.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_reset-text.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_resize.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_responsive-visibility.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_size.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_tab-focus.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_table-row.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_text-emphasis.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_text-overflow.scss
/usr/lib64/R/library/bslib/lib/bs3/assets/stylesheets/bootstrap/mixins/_vendor-prefixes.scss
/usr/lib64/R/library/bslib/lib/bs3/eyeglass-exports.js
/usr/lib64/R/library/bslib/lib/bs3/package.json
/usr/lib64/R/library/bslib/lib/bs4/LICENSE
/usr/lib64/R/library/bslib/lib/bs4/README.md
/usr/lib64/R/library/bslib/lib/bs4/dist/js/bootstrap.bundle.min.js
/usr/lib64/R/library/bslib/lib/bs4/dist/js/bootstrap.bundle.min.js.map
/usr/lib64/R/library/bslib/lib/bs4/package.json
/usr/lib64/R/library/bslib/lib/bs4/scss/_alert.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_badge.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_breadcrumb.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_button-group.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_card.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_carousel.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_close.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_code.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_custom-forms.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_deprecated.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_dropdown.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_forms.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_functions.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_grid.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_images.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_input-group.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_jumbotron.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_media.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_mixins.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_modal.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_nav.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_navbar.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_popover.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_print.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_progress.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_reboot.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_root.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_spinners.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_tables.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_toasts.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_tooltip.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_transitions.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_type.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_utilities.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/_variables.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/bootstrap-grid.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/bootstrap-reboot.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/bootstrap.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_alert.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_background-variant.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_badge.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_border-radius.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_box-shadow.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_breakpoints.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_caret.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_deprecate.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_float.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_forms.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_gradients.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_grid-framework.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_grid.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_hover.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_image.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_lists.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_nav-divider.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_reset-text.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_resize.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_screen-reader.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_size.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_table-row.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_text-emphasis.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_text-hide.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_text-truncate.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_transition.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/mixins/_visibility.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_align.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_background.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_borders.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_display.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_embed.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_flex.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_float.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_interactions.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_overflow.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_position.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_screenreaders.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_shadows.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_sizing.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_spacing.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_stretched-link.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_text.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/utilities/_visibility.scss
/usr/lib64/R/library/bslib/lib/bs4/scss/vendor/_rfs.scss
/usr/lib64/R/library/bslib/lib/bs5/LICENSE
/usr/lib64/R/library/bslib/lib/bs5/README.md
/usr/lib64/R/library/bslib/lib/bs5/dist/js/bootstrap.bundle.min.js
/usr/lib64/R/library/bslib/lib/bs5/dist/js/bootstrap.bundle.min.js.map
/usr/lib64/R/library/bslib/lib/bs5/package.json
/usr/lib64/R/library/bslib/lib/bs5/scss/_accordion.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_alert.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_badge.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_breadcrumb.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_button-group.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_card.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_carousel.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_close.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_containers.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_dropdown.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_forms.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_functions.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_grid.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_helpers.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_images.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_mixins.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_modal.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_nav.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_navbar.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_offcanvas.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_placeholders.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_popover.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_progress.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_reboot.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_root.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_spinners.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_tables.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_toasts.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_tooltip.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_transitions.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_type.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_utilities.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/_variables.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/bootstrap-grid.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/bootstrap-reboot.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/bootstrap-utilities.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/bootstrap.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_floating-labels.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-check.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-control.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-range.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-select.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_form-text.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_input-group.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_labels.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/forms/_validation.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_colored-links.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_position.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_ratio.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_stacks.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_stretched-link.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_text-truncation.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_visually-hidden.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/helpers/_vr.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_alert.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_backdrop.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_border-radius.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_box-shadow.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_breakpoints.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_buttons.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_caret.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_clearfix.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_color-scheme.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_container.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_deprecate.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_forms.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_gradients.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_grid.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_image.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_list-group.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_lists.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_pagination.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_reset-text.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_resize.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_table-variants.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_text-truncate.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_transition.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_utilities.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/mixins/_visually-hidden.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/utilities/_api.scss
/usr/lib64/R/library/bslib/lib/bs5/scss/vendor/_rfs.scss
/usr/lib64/R/library/bslib/lib/bsw3/LICENSE
/usr/lib64/R/library/bslib/lib/bsw3/README.md
/usr/lib64/R/library/bslib/lib/bsw3/cerulean/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/cerulean/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/cosmo/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/cosmo/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/cosmo/font.css
/usr/lib64/R/library/bslib/lib/bsw3/cyborg/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/cyborg/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/cyborg/font.css
/usr/lib64/R/library/bslib/lib/bsw3/darkly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/darkly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/darkly/font.css
/usr/lib64/R/library/bslib/lib/bsw3/flatly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/flatly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/flatly/font.css
/usr/lib64/R/library/bslib/lib/bsw3/journal/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/journal/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/journal/font.css
/usr/lib64/R/library/bslib/lib/bsw3/lumen/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/lumen/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/lumen/font.css
/usr/lib64/R/library/bslib/lib/bsw3/package.json
/usr/lib64/R/library/bslib/lib/bsw3/paper/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/paper/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/paper/font.css
/usr/lib64/R/library/bslib/lib/bsw3/readable/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/readable/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/readable/font.css
/usr/lib64/R/library/bslib/lib/bsw3/sandstone/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/sandstone/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/sandstone/font.css
/usr/lib64/R/library/bslib/lib/bsw3/simplex/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/simplex/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/simplex/font.css
/usr/lib64/R/library/bslib/lib/bsw3/slate/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/slate/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/spacelab/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/spacelab/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/spacelab/font.css
/usr/lib64/R/library/bslib/lib/bsw3/superhero/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/superhero/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/superhero/font.css
/usr/lib64/R/library/bslib/lib/bsw3/united/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/united/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/united/font.css
/usr/lib64/R/library/bslib/lib/bsw3/yeti/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw3/yeti/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw3/yeti/font.css
/usr/lib64/R/library/bslib/lib/bsw4/LICENSE
/usr/lib64/R/library/bslib/lib/bsw4/README.md
/usr/lib64/R/library/bslib/lib/bsw4/dist/cerulean/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cerulean/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cosmo/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cosmo/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cosmo/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/cyborg/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cyborg/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/cyborg/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/darkly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/darkly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/darkly/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/flatly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/flatly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/flatly/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/journal/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/journal/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/journal/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/litera/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/litera/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lumen/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lumen/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lumen/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/lux/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lux/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/lux/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/materia/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/materia/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/materia/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/minty/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/minty/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/minty/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/pulse/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/pulse/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sandstone/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sandstone/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sandstone/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/simplex/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/simplex/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/simplex/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/sketchy/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sketchy/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/sketchy/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/slate/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/slate/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/solar/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/solar/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/solar/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/spacelab/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/spacelab/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/spacelab/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/superhero/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/superhero/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/superhero/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/united/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/united/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/united/font.css
/usr/lib64/R/library/bslib/lib/bsw4/dist/yeti/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/yeti/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw4/dist/yeti/font.css
/usr/lib64/R/library/bslib/lib/bsw4/package.json
/usr/lib64/R/library/bslib/lib/bsw5/LICENSE
/usr/lib64/R/library/bslib/lib/bsw5/README.md
/usr/lib64/R/library/bslib/lib/bsw5/dist/cerulean/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cerulean/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cosmo/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cosmo/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cosmo/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/cyborg/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cyborg/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/cyborg/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/darkly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/darkly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/darkly/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/flatly/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/flatly/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/flatly/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/journal/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/journal/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/journal/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/litera/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/litera/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lumen/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lumen/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lumen/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/lux/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lux/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/lux/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/materia/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/materia/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/materia/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/minty/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/minty/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/minty/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/morph/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/morph/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/morph/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/pulse/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/pulse/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/quartz/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/quartz/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sandstone/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sandstone/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sandstone/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/simplex/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/simplex/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/simplex/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/sketchy/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sketchy/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/sketchy/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/slate/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/slate/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/solar/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/solar/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/solar/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/spacelab/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/spacelab/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/spacelab/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/superhero/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/superhero/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/superhero/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/united/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/united/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/united/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/vapor/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/vapor/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/vapor/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/yeti/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/yeti/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/yeti/font.css
/usr/lib64/R/library/bslib/lib/bsw5/dist/zephyr/_bootswatch.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/zephyr/_variables.scss
/usr/lib64/R/library/bslib/lib/bsw5/dist/zephyr/font.css
/usr/lib64/R/library/bslib/lib/bsw5/package.json
/usr/lib64/R/library/bslib/nav-spacer/nav-spacer.scss
/usr/lib64/R/library/bslib/package.json
/usr/lib64/R/library/bslib/rmarkdown/templates/bs4/skeleton/skeleton.html
/usr/lib64/R/library/bslib/rmarkdown/templates/legacy/skeleton/skeleton.Rmd
/usr/lib64/R/library/bslib/rmarkdown/templates/legacy/template.yaml
/usr/lib64/R/library/bslib/rmarkdown/templates/new/skeleton/skeleton.Rmd
/usr/lib64/R/library/bslib/rmarkdown/templates/new/template.yaml
/usr/lib64/R/library/bslib/rmarkdown/templates/real-time/skeleton/skeleton.Rmd
/usr/lib64/R/library/bslib/rmarkdown/templates/real-time/template.yaml
/usr/lib64/R/library/bslib/sass-utils/color-contrast.scss
/usr/lib64/R/library/bslib/tests/testthat.R
/usr/lib64/R/library/bslib/tests/testthat/_snaps/page.md
/usr/lib64/R/library/bslib/tests/testthat/_snaps/zzzz-bs-sass/bs4-imports
/usr/lib64/R/library/bslib/tests/testthat/_snaps/zzzz-bs-sass/bs5-imports
/usr/lib64/R/library/bslib/tests/testthat/helper-cache.R
/usr/lib64/R/library/bslib/tests/testthat/helper-css.R
/usr/lib64/R/library/bslib/tests/testthat/helper-files.R
/usr/lib64/R/library/bslib/tests/testthat/test-bs4-deps.R
/usr/lib64/R/library/bslib/tests/testthat/test-fonts.R
/usr/lib64/R/library/bslib/tests/testthat/test-global.R
/usr/lib64/R/library/bslib/tests/testthat/test-page.R
/usr/lib64/R/library/bslib/tests/testthat/test-remove.R
/usr/lib64/R/library/bslib/tests/testthat/test-rmd-skeletons.R
/usr/lib64/R/library/bslib/tests/testthat/test-shiny-devmode.R
/usr/lib64/R/library/bslib/tests/testthat/test-theme-base-colors.R
/usr/lib64/R/library/bslib/tests/testthat/test-theme-bootswatch.R
/usr/lib64/R/library/bslib/tests/testthat/test-theme-update.R
/usr/lib64/R/library/bslib/tests/testthat/test-theme-version.R
/usr/lib64/R/library/bslib/tests/testthat/test-utils.R
/usr/lib64/R/library/bslib/tests/testthat/test-zzz-bs.R
/usr/lib64/R/library/bslib/tests/testthat/test-zzz-precompile.R
/usr/lib64/R/library/bslib/tests/testthat/test-zzzz-bs-sass.R
/usr/lib64/R/library/bslib/themer-demo/app.R
/usr/lib64/R/library/bslib/themer-demo/deploy.R
/usr/lib64/R/library/bslib/themer-demo/deploy/app.R
/usr/lib64/R/library/bslib/themer-demo/deploy/rsconnect/connect.rstudioservices.com/carson/themer-demo.dcf
/usr/lib64/R/library/bslib/themer-demo/deploy/rsconnect/shinyapps.io/testing-apps/themer-demo.dcf
/usr/lib64/R/library/bslib/themer-demo/global.R
/usr/lib64/R/library/bslib/themer/options.json
/usr/lib64/R/library/bslib/themer/themer.js
/usr/lib64/R/library/bslib/themer/themer.scss
